version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nestjs
    restart: always

volumes:
  db_data: {}